name: Publish Python Package

on:
  push:
    tags:
      - 'v*'      # Matches v1.0.0, v2.1.0-rc1, etc.
      - '*.*.*'   # Matches 1.0.0, 2.1.3, etc. (optional)

jobs:
  pypi-publish:
    name: Upload Release to PyPI
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/analyzemft

    permissions:
      id-token: write 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: Verify version matches tag
      run: |
        TAG_REF="${GITHUB_REF#refs/tags/}"
        TAG_VERSION="${TAG_REF#v}"  # Remove 'v' prefix if present
        PACKAGE_VERSION=$(python -c "from src.analyzeMFT import __version__; print(__version__)")
        echo "Tag version: $TAG_VERSION"
        echo "Package version: $PACKAGE_VERSION"
        if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
          echo " [[ERROR]] Version mismatch: tag '$TAG_VERSION' != package '$PACKAGE_VERSION'"
          exit 1
        fi

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.9.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip_existing: true