name: Publish AnalyzeMFT Package

on:
  push:
    tags:
      - 'v*'        # e.g., v1.0.0, v2.1.3
      - '*.*.*'     # e.g., 1.0.0 (optional)

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/analyzemft
    permissions:
      id-token: write  
      

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Verify version matches tag
      run: |
        TAG_NAME="${GITHUB_REF_NAME}"
        TAG_VERSION="${TAG_NAME#v}"  # Remove 'v' prefix
        PACKAGE_VERSION=$(python -c "from src.analyzeMFT import __version__; print(__version__)")
        echo "Tag version: $TAG_VERSION"
        echo "Package version: $PACKAGE_VERSION"
        if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
          echo "[[ERROR]] Version mismatch: tag '$TAG_VERSION' != package '$PACKAGE_VERSION'"
          exit 1
        fi

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: |
        python -m build

    - name: Check package integrity
      run: |
        twine check dist/*

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.9.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip_existing: true  # Prevents error if version already exists